---
name: continuous_integration

on:
  - push

jobs:
  tests_and_linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set Node.js.
        uses: actions/setup-node@master
        with:
          node-version: 12
      - name: Install global dependencies.
        run: npm i -g gatsby-cli yarn typescript
      - name: Install dependencies.
        run: yarn install
      - name: Run linting.
        run: yarn lint
      - name: Run TypeScript type checking.
        run: yarn check-types
      - name: Run integration tests with cypress.
        uses: cypress-io/github-action@master
        with:
          start: yarn dev
          wait-on: http://localhost:8000
      - name: Build the application.
        run: yarn build
